# Start from base image
FROM golang:alpine

# Set the current working directory inside the container
WORKDIR /app

# Copy go mod and sum files
COPY go.mod ./
COPY go.sum ./

# Download all dependencies
RUN go mod download

# Copy source from current directory to working directory
COPY . .

# Build the application
RUN go build -o ./ ./cmd/main ./...

# Expose necessary port
EXPOSE 3000

# Waiting for mysql db
ENV WAIT_VERSION 2.7.2
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/$WAIT_VERSION/wait /wait
RUN chmod +x /wait

# Run the created binary executable after wait for mysql container to be up
CMD ["./main"]